### ISSUE TITLE
Support py3.12

### ISSUE THREAD

**Issue by chenrui333** [fanout/zurl#25]
While trying to migrate zurl to test against py3.12, ran into the following test failure

```
    zmq/backend/cython/_device.c: In function ‘__Pyx_Raise’:
    zmq/backend/cython/_device.c:4372:34: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘curexc_traceback’
     4372 |         PyObject* tmp_tb = tstate->curexc_traceback;
          |                                  ^~
    zmq/backend/cython/_device.c:4375:19: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘curexc_traceback’
     4375 |             tstate->curexc_traceback = tb;
          |                   ^~
    zmq/backend/cython/_device.c: In function ‘__Pyx_PyInt_As_int’:
    zmq/backend/cython/_device.c:5408:53: error: ‘PyLongObject’ {aka ‘struct _longobject’} has no member named ‘ob_digit’
     5408 |             const digit* digits = ((PyLongObject*)x)->ob_digit;
          |                                                     ^~
    zmq/backend/cython/_device.c:5463:53: error: ‘PyLongObject’ {aka ‘struct _longobject’} has no member named ‘ob_digit’
     5463 |             const digit* digits = ((PyLongObject*)x)->ob_digit;
          |                                                     ^~
    zmq/backend/cython/_device.c: In function ‘__Pyx_PyInt_As_long’:
    zmq/backend/cython/_device.c:5680:53: error: ‘PyLongObject’ {aka ‘struct _longobject’} has no member named ‘ob_digit’
     5680 |             const digit* digits = ((PyLongObject*)x)->ob_digit;
          |                                                     ^~
    zmq/backend/cython/_device.c:5735:53: error: ‘PyLongObject’ {aka ‘struct _longobject’} has no member named ‘ob_digit’
     5735 |             const digit* digits = ((PyLongObject*)x)->ob_digit;
          |                                                     ^~
    zmq/backend/cython/_device.c: In function ‘__Pyx_PyIndex_AsSsize_t’:
    zmq/backend/cython/_device.c:6086:45: error: ‘PyLongObject’ {aka ‘struct _longobject’} has no member named ‘ob_digit’
     6086 |     const digit* digits = ((PyLongObject*)b)->ob_digit;
          |                                             ^~
    ************************************************
    ************************************************
    error: command '/usr/bin/gcc-11' failed with exit code 1
    error: subprocess-exited-with-error
```

log, https://github.com/Homebrew/homebrew-core/actions/runs/6450154450/job/17509259440?pr=150232
relates to https://github.com/Homebrew/homebrew-core/pull/150232

**Comment by jkarneges** [comment]
Hi, the latest pyzmq (25.1.1) works with python 3.12 for me. The formula refers to pyzmq 24.0.1.
